# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-09 14:24
from __future__ import unicode_literals

import common.utils
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.CharField(default=common.utils.gen_uuid, max_length=50, primary_key=True, serialize=False,
                                        verbose_name='uuid \u552f\u4e00\u6807\u793a\u7b26')),
                ('create_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now,
                                                     verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modify_time', models.DateTimeField(auto_now=True, db_index=True, null=True,
                                                     verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('is_delete',
                 models.BooleanField(db_index=True, default=False, verbose_name='\u5220\u9664\u6807\u8bb0')),
                (
                    'delete_time',
                    models.DateTimeField(db_index=True, null=True, verbose_name='\u5220\u9664\u65f6\u95f4')),
                ('name', models.CharField(max_length=100)),
                ('instance_uuid', models.CharField(max_length=50)),
                ('instance_name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=200)),
                ('cpu_core', models.IntegerField()),
                ('vnc_port', models.IntegerField()),
                ('mem_size_kb', models.BigIntegerField()),
                ('xml', models.TextField()),
                ('last_task_id', models.CharField(max_length=50)),
                ('last_task_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='HostNetwork',
            fields=[
                ('id', models.CharField(default=common.utils.gen_uuid, max_length=50, primary_key=True, serialize=False,
                                        verbose_name='uuid \u552f\u4e00\u6807\u793a\u7b26')),
                ('create_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now,
                                                     verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modify_time', models.DateTimeField(auto_now=True, db_index=True, null=True,
                                                     verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('is_delete',
                 models.BooleanField(db_index=True, default=False, verbose_name='\u5220\u9664\u6807\u8bb0')),
                (
                    'delete_time',
                    models.DateTimeField(db_index=True, null=True, verbose_name='\u5220\u9664\u65f6\u95f4')),
                ('mac', models.CharField(max_length=20)),
                ('network_name', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=50)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host_manager.Host')),
            ],
            options={
                'ordering': ['create_time'],
            },
        ),
        migrations.CreateModel(
            name='HostStorage',
            fields=[
                ('id', models.CharField(default=common.utils.gen_uuid, max_length=50, primary_key=True, serialize=False,
                                        verbose_name='uuid \u552f\u4e00\u6807\u793a\u7b26')),
                ('create_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now,
                                                     verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modify_time', models.DateTimeField(auto_now=True, db_index=True, null=True,
                                                     verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('is_delete',
                 models.BooleanField(db_index=True, default=False, verbose_name='\u5220\u9664\u6807\u8bb0')),
                (
                    'delete_time',
                    models.DateTimeField(db_index=True, null=True, verbose_name='\u5220\u9664\u65f6\u95f4')),
                ('device',
                 models.CharField(choices=[('disk', '\u786c\u76d8'), ('cdrom', '\u5149\u9a71')], max_length=10)),
                ('dev', models.CharField(max_length=20)),
                ('bus', models.CharField(max_length=20)),
                ('path', models.CharField(max_length=300)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host_manager.Host')),
            ],
            options={
                'ordering': ['create_time'],
            },
        ),
        migrations.CreateModel(
            name='VncPorts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ['-value'],
            },
        ),
    ]
