# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-09 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='last_task_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='last_task_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='xml',
            field=models.TextField(null=True),
        ),
    ]
