# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-09 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_manager', '0002_auto_20191209_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
