# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-10 17:27
from __future__ import unicode_literals

import common.utils
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('host_manager', '0003_auto_20191209_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostSnapshot',
            fields=[
                ('id', models.CharField(default=common.utils.gen_uuid, max_length=50, primary_key=True, serialize=False,
                                        verbose_name='uuid \u552f\u4e00\u6807\u793a\u7b26')),
                ('create_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now,
                                                     verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modify_time', models.DateTimeField(auto_now=True, db_index=True, null=True,
                                                     verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('is_delete',
                 models.BooleanField(db_index=True, default=False, verbose_name='\u5220\u9664\u6807\u8bb0')),
                (
                    'delete_time',
                    models.DateTimeField(db_index=True, null=True, verbose_name='\u5220\u9664\u65f6\u95f4')),
                ('instance_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('parent_instance_name', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=20, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host_manager.Host')),
            ],
            options={
                'ordering': ['create_time'],
            },
        ),
    ]
